academic/urls.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.conf.urls import url


# Third party apps imports


# Local imports
from .views import IndexView

# Create your tests here.


urlpatterns = [
    url(
        r'^$',
        IndexView.as_view(),
        name='index'
    ),
]

horarios/urls.py
# -*- coding: utf-8 -*-
"""horarios URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin

from main import urls as main_urls
from schools import urls as schools_urls

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(main_urls, namespace='main')),
    url(r'^', include(schools_urls, namespace='schools'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

main/urls.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.conf.urls import url


# Third party apps imports


# Local imports
from .views import IndexView

# Create your tests here.


urlpatterns = [
    url(
        r'^$',
        IndexView.as_view(),
        name='index'
    )
]

profiles/urls.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.conf.urls import url


# Third party apps imports


# Local imports
from .views import IndexView

# Create your tests here.


urlpatterns = [
    url(
        r'^$',
        IndexView.as_view(),
        name='index'
    ),
]

schools/urls.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.conf.urls import url


# Third party apps imports


# Local imports
from .views import SchoolCreateView

# Create your tests here.


urlpatterns = [
    url(
        r'^school/$',
        SchoolCreateView.as_view(),
        name='create'
    )
]

academic/models.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.db import models


# Third party apps imports


# Local imports


# Create your models here.
class Area(models.Model):

    hours = models.PositiveSmallIntegerField(u'Cantidad de horas académicas')
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre corto', max_length=10)

    class Meta:
        verbose_name = u'Área Académica'
        verbose_name_plural = u'Áreas Académicas'

    def __unicode__(self):
        return u'{}'.format(self.name)


class Course(models.Model):

    area = models.ForeignKey(Area)
    name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

    def __unicode__(self):
        return u'{}'.format(self.name)


class Teacher(models.Model):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    courses = models.ManyToManyField(Course)

    class Meta:
        verbose_name = 'Profesor'
        verbose_name_plural = 'Profesores'

    def __unicode__(self):
        return u'{}, {}'.format(self.last_name, self.first_name)

    def get_courses(self):
        return ', '.join([course.name for course in self.courses.all()])
    get_courses.short_description = 'Cursos'

main/models.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.db import models


# Third party apps imports


# Local imports


# Create your models here.

profiles/models.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.db import models


# Third party apps imports


# Local imports


# Create your models here.

schools/models.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.db import models


# Third party apps imports


# Local imports


# Create your models here.
class School(models.Model):

    LEVEL_CHOICES = (
        ('primaria', 'Primaria'),
        ('secundaria', 'Secundaria'),
    )

    break_time = models.PositiveSmallIntegerField('Minutos de recreo')
    classrooms = models.PositiveSmallIntegerField('Cantidad de aulas')
    hour_duration = models.PositiveSmallIntegerField(
        u'Minutos de duración de las horas académicas')
    hours = models.PositiveSmallIntegerField(u'Cantidad de horas académicas')
    level = models.CharField('Nivel', choices=LEVEL_CHOICES, max_length=10)
    name = models.CharField('Nombre', max_length=75)

    class Meta:
        verbose_name = 'Colegio'
        verbose_name_plural = 'Colegios'

    def __unicode__(self):
        return u'{}'.format(self.name)


class Classroom(models.Model):

    SECONDARY_CHOICES = (
        ('1', 'Primero'),
        ('2', 'Segundo'),
        ('3', 'Tercero'),
        ('4', 'Cuarto'),
        ('5', 'Quinto'), )

    PRIMARY_CHOICES = SECONDARY_CHOICES + (
        ('6', 'Sexto'), )

    grade = models.CharField('Grado', choices=PRIMARY_CHOICES, max_length=1)
    school = models.ForeignKey(School, verbose_name='Colegio')
    section = models.CharField('Seccion', max_length=1)

    class Meta:
        verbose_name = 'Grado'
        verbose_name_plural = 'Grados'
        unique_together = ['grade', 'school', 'section']

    def __unicode__(self):
        return u'{} {}'.format(self.grade, self.section)

    def save(self):
        self.section = self.section.upper()
        return super(Classroom, self).save()

academic/forms.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django import forms


# Third party apps imports


# Local imports


# Create your forms here.

main/forms.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django import forms


# Third party apps imports


# Local imports


# Create your forms here.

profiles/forms.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django import forms


# Third party apps imports


# Local imports


# Create your forms here.

schools/forms.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django import forms


# Third party apps imports
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


# Local imports
from .models import School


# Create your forms here.
class SchoolForm(forms.ModelForm):

    class Meta:
        model = School
        fields = (
            'name', 'level', 'classrooms', 'hours', 'hour_duration',
            'break_time', )

    def __init__(self, *args, **kwargs):
        super(SchoolForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Enviar'))

academic/views.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.views.generic.base import TemplateView


# Third party apps imports


# Local imports


# Create your views here.
class IndexView(TemplateView):
    template_name = 'academic/index.html'

main/views.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.views.generic.base import TemplateView


# Third party apps imports


# Local imports


# Create your views here.
class IndexView(TemplateView):

    template_name = 'main/index.html'

profiles/views.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.views.generic.base import TemplateView


# Third party apps imports


# Local imports


# Create your views here.
class IndexView(TemplateView):
    template_name = 'profiles/index.html'

schools/views.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.core.urlresolvers import reverse
from django.views.generic import CreateView
from django.views.generic.base import TemplateView


# Third party apps imports


# Local imports
from .forms import SchoolForm


# Create your views here.
class SchoolCreateView(CreateView):

    form_class = SchoolForm
    template_name = 'schools/create.html'

    def get_success_url(self):
        return reverse('main:index')

academic/templates/academic/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ app_name }} index page</title>
  </head>
  <body>
    <h1>{{ app_name }} index page</h1>
  </body>
</html>

main/templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'main/css/bootstrap-theme.min.css' %}" rel="stylesheet" media="screen">
    <title>{% block title %}{% endblock title %} | Generador de Horarios</title>
  </head>
  <body>
    <div class="page">
      <header class="site-header">
        {% block header %}{% endblock header %}
      </header>
      <div class="container">
        {% block content %}{% endblock content %}
      </div>
    </div>
    <script src="{% static 'main/js/jquery-2.2.2.min.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
  </body>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}



{% block title %}Inicio{% endblock title %}



{% block header %}
  {% include "main/partials/_navbar.html" with active_link='index' %}
{% endblock header %}



{% block content %}
  <h2>Inicio</h2>
{% endblock content %}

main/templates/main/partials/_navbar.html
<ul class="nav nav-pills">
  <li{% if active_link == "index" %} class="active"{% endif %}><a href="{% url 'main:index' %}">Inicio</a></li>
  <li{% if active_link == "school" %} class="active"{% endif %}><a href="{% url 'schools:create' %}">Colegio</a></li>
</ul>

profiles/templates/profiles/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ app_name }} index page</title>
  </head>
  <body>
    <h1>{{ app_name }} index page</h1>
  </body>
</html>

schools/templates/schools/create.html
{% extends "main/base.html" %}



{% block title %}Agregar Colegio{% endblock title %}



{% block header %}
  {% include "main/partials/_navbar.html" with active_link='school' %}
{% endblock header %}



{% block content %}
<div class="text-center">
  <h1>Agregar Colegio</h1>
</div>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    <form method="POST">{% csrf_token %}
      <div id="div_id_name" class="form-group">
        <label for="id_name" class="control-label requiredField">Nombre<span class="asteriskField">*</span> </label>
        <div class="controls">
          <input class="textinput textInput form-control" id="id_name" maxlength="75" name="name" type="text" required />
        </div>
        {% for error in form.name.errors %}
          <div class="alert alert-danger">
            <strong>{{ error|safe }}</strong>
          </div>
        {% endfor %}
      </div>
      <div id="div_id_level" class="form-group">
        <label for="id_level" class="control-label requiredField">Nivel<span class="asteriskField">*</span> </label>
        <div class="controls">
          <select class="select form-control" id="id_level" name="level" required >
            <option value="" selected="selected">---------</option>
            <option value="primaria">Primaria</option>
            <option value="secundaria">Secundaria</option>
          </select>
        </div>
        {% for error in form.level.errors %}
          <div class="alert alert-danger">
            <strong>{{ error|safe }}</strong>
          </div>
        {% endfor %}
      </div>
      <div id="div_id_classrooms" class="form-group">
        <label for="id_classrooms" class="control-label requiredField">Cantidad de aulas<span class="asteriskField">*</span> </label>
        <div class="controls">
          <input class="numberinput form-control" id="id_classrooms" min="0" name="classrooms" type="number" required />
        </div>
        {% for error in form.classrooms.errors %}
          <div class="alert alert-danger">
            <strong>{{ error|safe }}</strong>
          </div>
        {% endfor %}
      </div>
      <div id="div_id_hours" class="form-group">
        <label for="id_hours" class="control-label requiredField">Cantidad de horas académicas<span class="asteriskField">*</span> </label>
        <div class="controls ">
          <input class="numberinput form-control" id="id_hours" min="0" name="hours" type="number" required />
        </div>
        {% for error in form.hours.errors %}
          <div class="alert alert-danger">
            <strong>{{ error|safe }}</strong>
          </div>
        {% endfor %}
      </div>
      <div id="div_id_hour_duration" class="form-group">
        <label for="id_hour_duration" class="control-label requiredField">Minutos de duración de las horas académicas<span class="asteriskField">*</span> </label>
        <div class="controls">
          <input class="numberinput form-control" id="id_hour_duration" min="0" name="hour_duration" type="number" required />
        </div>
        {% for error in form.hour_duration.errors %}
          <div class="alert alert-danger">
            <strong>{{ error|safe }}</strong>
          </div>
        {% endfor %}
      </div>
      <div id="div_id_break_time" class="form-group">
        <label for="id_break_time" class="control-label requiredField">Minutos de recreo<span class="asteriskField">*</span> </label>
        <div class="controls">
          <input class="numberinput form-control" id="id_break_time" min="0" name="break_time" type="number" required />
        </div>
        {% for error in form.break_time.errors %}
          <div class="alert alert-danger">
            <strong>{{ error|safe }}</strong>
          </div>
        {% endfor %}
      </div>
      <div class="form-group">
        <div class="controls text-center">
          <input type="submit" name="submit" value="Enviar" class="btn btn-primary" id="submit-id-submit" />
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}